#此配置文件自定义配置oss的默认属性

alibaba:
  cloud:
    oss:
      default:
        #必要初始化属性
        accessKeyId: LTAIpn6Ibg2sFwhV
        accessKeySecret: XuJZLedVaeHUsmHZOtmHgSkM7J2FTf
        endpoint: oss-cn-hangzhou.aliyuncs.com
        #非必要初始化属性
        bucketName: my-first-bk2
        #不能添加httpL://字段
        callbackDomain: kue6kt.natappfree.cc

        #以下为可选配置
        #用户代理，指HTTP的User-Agent头。默认为”aliyun-sdk-java”
        userAgent:
        #代理服务器主机地址
        proxyHost:
        #代理服务器端口
        proxyPort:
        #代理服务器验证的用户名
        proxyUsername:
        #代理服务器验证的密码
        proxyPassword:
        #访问NTLM验证的代理服务器的Windows域名
        ProxyDomain:
        #NTLM代理服务器的Windows工作站名称
        proxyWorkstation:
        #允许打开的最大HTTP连接数。默认为1024
        maxConnections:
        #通过打开的连接传输数据的超时时间（单位：毫秒）。默认为50000毫秒
        socketTimeout:
        #建立连接的超时时间（单位：毫秒）。默认为50000毫秒
        connectionTimeout: 10000
        #可重试的请求失败后最大的重试次数。默认为3次
        maxErrorRetry: 5


